name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  paths:
    - "./package-*.json"
    - "./tsconfig.json"
    - "src/**/*.ts"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "15"
      - run: npm ci
      - run: npm test
